version: '3'

services:
   db:
      image: postgres
      restart: always
   adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080
   web:
      image: starofthemoon/portfolio:1.1
      command: /bin/bash -c "sleep 40;python manage.py runserver 0.0.0.0:8000"
      volumes:
         - "./app:/app/app"
         - "./locale:/app/locale"
         - "./portfolio:/app/portfolio"
      ports:
         - "8000:8000"
      depends_on:
         - db
         - adminer
   